import { API_ROUTES } from '../apiRoute'

export const AD_API = {
  GET_STATES: `${API_ROUTES.VGC_USERS_PREFIX}/allStates`,
  GET_CATEGORIES: `${API_ROUTES.VGC_USERS_PREFIX}/getAllCategories`,
  CREATE_NEW_JOB: `${API_ROUTES.VGC_USERS_PREFIX}/createNewJobByUser`,
  GET_JOBS_BY_USER: `${API_ROUTES.VGC_USERS_PREFIX}/getListJobsByUser`,
  GET_JOBS_APPLIED: `${API_ROUTES.VGC_USERS_PREFIX}/getJobApplied`,
}
